module.exports = {
  MIXQL_SELECT: 'SELECT ',
  MIXQL_CREATE_SALT: 'CREATE SALT',
  MIXQL_CREATE_KEY: 'CREATE KEY',
  MIXQL_CREATE_UUID: 'CREATE UUID',

  MIXQL_STORE_LIST: 'STORE LIST',
  MIXQL_STORE_SELECT: 'STORE SELECT ',
  MIXQL_STORE_USE: 'STORE USE ',
  MIXQL_STORE_DELETE: 'STORE DELETE ',

  MIXQL_ASHASH: ' AS hash',
  MIXQL_LIMIT: ' LIMIT ',
  MIXQL_LENGTH: ' LENGTH ',
  MIXQL_SHA: ' SHA',
  MIXQL_UPPERCASE: 'UPPERCASE',
  MIXQL_STOREAS: ' STORE AS ',
  MIXQL_STORED_QUERIES: 'STORED QUERIES',
  MIXQL_AUTH: 'AUTH ',
  MIXQL_KEY: ' KEY ',
  MIXQL_SALT: ' SALT ',
  MIXQL_PEPPER: ' PEPPER ',
};
